---
title: "word_manipulation.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
so I copied the first rows to atom https://baike.baidu.com/item/%E6%96%B0%E7%99%BE%E5%AE%B6%E5%A7%93
manualy removed the white space,
replaced \n with nothing,
replaced (.{1}) with '小$1', 
```{r}
a = c('小李', '小王', '小张', '小刘', '小陈', '小杨', '小赵', '小黄', '小周', '小吴', '小徐', '小孙', '小胡', '小朱', '小高', '小林', '小何', '小郭', '小马', '小罗', '小梁', '小宋', '小郑', '小谢', '小韩', '小唐', '小冯', '小于', '小董', '小萧', '小程', '小曹', '小袁', '小邓', '小许', '小傅', '小沈', '小曾', '小彭', '小吕', '小苏', '小卢', '小蒋', '小蔡', '小贾', '小丁', '小魏', '小薛', '小叶', '小阎', '小余', '小潘', '小杜', '小戴', '小夏', '小钟', '小汪', '小田', '小任', '小姜', '小范', '小方', '小石', '小姚', '小谭', '小廖', '小邹', '小熊', '小金', '小陆', '小郝', '小孔', '小白', '小崔', '小康', '小毛', '小邱', '小秦', '小江', '小史')

# sort doesn't sort it correclty

# http://x.shahaizi.com/infos/w2qiming/11/9897-1.html
# 小力 小强 小洪  小宏 小东 小刚 小华 小亮 小柯 小烨 小草 小科 小东 小庄 小林 小风 小峰 小坤 小豪 小木 小龙 小武 小富 小鹏 小雷 小渊 小雨 小豪 小浩 小皓 小河 小禾
# 
# 小花 小红 小虹 小如 小茹 小妍 小娜 小芬 小芳 小云 小芸 小丽 小莉 小俐 小丹 小凤 小樱 小莹 小英 小茵 小英 小芙 小琳 小玲 小蕾 小娟 小蓓 小婵
b = sample(a)
dput(b)

```
https://news.sina.cn/2017-08-12/detail-ifyixipt1325151.d.html?from=wap


```{r}
# neutral 　杰 敏 涛 
# surname 张王李刘 

f = dput(unique(c("王芳", "李娜", "张敏", "李静", "李梅", "张丽", "王静", "张静", "李敏", "王敏", "王丽", "李娟", "张艳", "李燕", "王娟", "李霞", "刘敏", "李丽", "刘芳", "张悦", "李妍")))

m = dput(unique(c("张伟", "王伟", "李伟", "刘伟", "李强", "张磊", "王磊", "李军", "刘洋", "王勇", "张勇", "王艳", "李杰", "王强", "王军", "张杰", "张涛", "王涛", "李明", "王超", "李勇", "刘杰", "张军", "张强", "王平", "王刚", "王杰")))

```

```{r}
# a = c("ANNIE", "BENNY", "BETTY", "BONNIE", "BRANDY", "CARLIE", "CHLOE",
#       "COREY", "DANNY", "DOLLY", "DORRY", "DORY", "FANNY", "HARLEY",
#       "JENNY", "JUDY", "KERRY", "KIMMY", "LACEY", "LAURIE", "LINDY",
#       "LONNIE", "MANDY", "MARY", "MERRY", "MINDY", "MOLLY", "MORRIE",
#       "NELLY", "PAMMY", "PENNY", "RONNIE", "ROONIE", "SANDY", "SANNDY",
#       "TAMMY", "TIMMY", "TORI")
# 
# b = c("RUDY","EDDIE", "KENNY", "TERRY","KELLY", "BILLY", "ANDY", "LARRY", "FREDDY", "BILLY", "ANDY", "JERRY", "WALLY", "TEDDY", "OLLIE", "GARRY", "JOHNNY", "CODY", "HARVEY", "DONNY", "PERCY", "WILLY", "WALLY")
# 
# c = c("FRANNY", "CASEY")
# 
# d = c(a, b, c)
# 
# g = unique(d)
# 
# e = c("PAMMY", "JUDY", "TIMMY", "MANDY", "WALLY", "LONNIE", "BILLY",
#       "HARVEY", "SANNDY", "FRANNY", "KIMMY", "BILLY", "DOLLY", "FREDDY",
#       "SANDY", "OLLIE", "TORI", "BRANDY", "PERCY", "MERRY", "EDDIE",
#       "FANNY", "RUDY", "COREY", "KERRY", "BETTY", "LACEY", "JERRY",
#       "LARRY", "LAURIE", "PENNY", "MOLLY", "DANNY", "ROONIE", "MARY",
#       "RONNIE", "CASEY", "TERRY", "MINDY", "TAMMY", "NELLY", "ANNIE",
#       "GARRY", "LINDY", "DORY", "BENNY", "ANDY", "WALLY", "DONNY",
#       "JENNY", "WILLY", "MORRIE", "JOHNNY", "BONNIE", "KENNY", "ANDY",
#       "CODY", "HARLEY", "KELLY", "CARLIE", "CHLOE", "DORRY", "TEDDY")
# 
# f = unique(e)
# 
# missing = setdiff(g, f)
# 
# 
# g [!(g %in% f)] 

female= sort(c("PAMMY", "JUDY", "MANDY", "SANNDY", "FRANNY", "KIMMY", "DOLLY", "SANDY", "TORI", "BRANDY", "MERRY", "FANNY", "RUDY", "BETTY", "LACEY", "LARRY", "LAURIE", "PENNY", "MOLLY", "MARY", "MARY", "JENNY", "BONNIE", "KELLY", "CARLIE", "CHLOE", "DORRY", "MINDY", "ANNIE", "LINDY", "DORY"))


male = sort(c("TIMMY", "WALLY", "LONNIE", "BILLY", "HARVEY", "FREEDY", "OLLIE", "PERCY", "EDDIE", "COREY", "JERRY", "DANNY", "RONNIE", "DONNY", "WILLY", "JOHNNY", "KENNY", "ANDY", "CODY", "TEDDY", "TAMMY", "GARRY"))

# KERRY, ROONIE, CASEY, ROONIE, CASEY, MORRIE, HARLEY, TERRY, NELLY, BENNY

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
        sep="", collapse=" ")
}

simpleLow <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(substring(s, 1,1), tolower(substring(s, 2)),
        sep="", collapse=" ")
}

a = sapply(female, simpleLow)

dput(unname(a))

```

some old junk from my python file
```{r}
    # female_names = ["ANNIE", "BETTY", "BONNIE", "BRANDY", "CARLIE", "CHLOE", "DOLLY",
    # "DORRY", "DORY", FRANNY", "JENNY", "JUDY", "KELLY",
    # "KIMMY", "LACEY", "LARRY", "LAURIE", "LINDY", "MANDY", "MARY",
    # "MERRY", "MINDY", "MOLLY", "PAMMY", "PENNY", "RUDY", "SANDY",
    # "TORI"]
    # male_names = ["ANDY", "BILLY", "CODY", "COREY", "DANNY", "DONNY", "EDDIE",
    # "Freddy", "GARY", "HARVEY", "JERRY", "JOHNNY", "KENNY", "LONNIE",
    # "OLLIE", "PERCY", "RONNIE", "TAMMY", "TEDDY", "TIMMY", "WALLY",
    # "WILLY"]
    #
    # other names, cindy, nancy, zoey, morrie, joey, willy, randy, tracey, casey, terry, kerry, kylie, darcy, neddy, mory, benny, manny, jilly, nelly, carrie, hailey, sammy
    # names i threw out myself, fanny, SANDY, dorry

    # lily,




    #    a small pool to test the latter any trial with characters of the same name? test
    #    names = {'F': ["Annie", "Betty", "Bonnie", "Brandy", "Carlie", "Chloe", "Dolly", "Dory", "Franny", "Jenny", "Judy",
    #                   "Kelly"],
    #             'M': ["Andy", "Billy", "Cody", "Corey", "Danny", "Donny", "Eddie",
    #                   "Freddy", "GARY", "Harvey"]}
    #    ted thinks ambiguous or bad sandy, andy, dory, larry, rudy, tammy, willy, dolly, lindy, pammy, lonnie, morrie, randy, casey, terry, mary, merry



```
