---
title: "word_manipulation.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# a = c("ANNIE", "BENNY", "BETTY", "BONNIE", "BRANDY", "CARLIE", "CHLOE",
#       "COREY", "DANNY", "DOLLY", "DORRY", "DORY", "FANNY", "HARLEY",
#       "JENNY", "JUDY", "KERRY", "KIMMY", "LACEY", "LAURIE", "LINDY",
#       "LONNIE", "MANDY", "MARY", "MERRY", "MINDY", "MOLLY", "MORRIE",
#       "NELLY", "PAMMY", "PENNY", "RONNIE", "ROONIE", "SANDY", "SANNDY",
#       "TAMMY", "TIMMY", "TORI")
# 
# b = c("RUDY","EDDIE", "KENNY", "TERRY","KELLY", "BILLY", "ANDY", "LARRY", "FREDDY", "BILLY", "ANDY", "JERRY", "WALLY", "TEDDY", "OLLIE", "GARRY", "JOHNNY", "CODY", "HARVEY", "DONNY", "PERCY", "WILLY", "WALLY")
# 
# c = c("FRANNY", "CASEY")
# 
# d = c(a, b, c)
# 
# g = unique(d)
# 
# e = c("PAMMY", "JUDY", "TIMMY", "MANDY", "WALLY", "LONNIE", "BILLY",
#       "HARVEY", "SANNDY", "FRANNY", "KIMMY", "BILLY", "DOLLY", "FREDDY",
#       "SANDY", "OLLIE", "TORI", "BRANDY", "PERCY", "MERRY", "EDDIE",
#       "FANNY", "RUDY", "COREY", "KERRY", "BETTY", "LACEY", "JERRY",
#       "LARRY", "LAURIE", "PENNY", "MOLLY", "DANNY", "ROONIE", "MARY",
#       "RONNIE", "CASEY", "TERRY", "MINDY", "TAMMY", "NELLY", "ANNIE",
#       "GARRY", "LINDY", "DORY", "BENNY", "ANDY", "WALLY", "DONNY",
#       "JENNY", "WILLY", "MORRIE", "JOHNNY", "BONNIE", "KENNY", "ANDY",
#       "CODY", "HARLEY", "KELLY", "CARLIE", "CHLOE", "DORRY", "TEDDY")
# 
# f = unique(e)
# 
# missing = setdiff(g, f)
# 
# 
# g [!(g %in% f)] 

female= c("PAMMY", "JUDY", "MANDY", "SANNDY", "FRANNY", "KIMMY", "DOLLY", "SANDY", "TORI", "BRANDY", "MERRY", "FANNY", "RUDY", "BETTY", "LACEY", "LARRY", "LAURIE", "PENNY", "MOLLY", "MARY", "MARY", "JENNY", "BONNIE", "KELLY", "CARLIE", "CHLOE", "DORRY", "MINDY", "ANNIE", "LINDY", "DORY")


male = c("TIMMY", "WALLY", "LONNIE", "BILLY", "HARVEY", "FREEDY", "OLLIE", "PERCY", "EDDIE", "COREY", "JERRY", "DANNY", "RONNIE", "DONNY", "WILLY", "JOHNNY", "KENNY", "ANDY", "CODY", "TEDDY", "TAMMY", "GARRY")

# KERRY, ROONIE, CASEY, ROONIE, CASEY, MORRIE, HARLEY, TERRY, NELLY, BENNY

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
        sep="", collapse=" ")
}

simpleLow <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(substring(s, 1,1), tolower(substring(s, 2)),
        sep="", collapse=" ")
}

a = sapply(male, simpleLow)


```