---
title: "acoustic_analysis"
output:
  pdf_document: default
  html_document: default
---


```{r message=FALSE, warning=FALSE, tidy=TRUE, echo = FALSE}
library(dplyr)
library(lme4)
library(zeallot)
library(Rmisc)
library(ggplot2)
library(plyr)
library(formatR)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy = TRUE)


normalize_data = function(df, remove_outliers){
  for(col_name in features){
    if(!is.numeric(df[[col_name]])){
      df[[col_name]] = as.numeric(df[[col_name]])
    }
    df[[col_name]] = scale(df[[col_name]])
    # there is surge of na after the first colling of the above line. tested by print(sum(is.na(df_Agent))). I guess it's because the df is nibble
    # print(sum(is.na(df_Agent)))
    
  }
  for(col_name in features){
    
    if(remove_outliers){
      df = df[df[[col_name]]>-2 & df[[col_name]]<2,]
      # print(sum(is.na(df_Agent)))
      
    }
  }
  return(df)
}

process_data_with_yes = function(df){
    # df = normalize_data(df, bRemove_outliers)

  if(cur_exp %in% c("exp4", "exp6", "exp8", "exp9")){
    df_Agent = df[(df$location_condition=='Agent' | df$location_condition=='Control') & df$word_num=='2',]
    # df_Agent inheri row hum from df
    
    df_Verb = df[(df$location_condition=='Agent'| df$location_condition=='Control') & df$word_num=='4',]
    
    df_Patient = df[(df$location_condition=='Agent'| df$location_condition=='Control') & df$word_num=='5',]    
  } else if(cur_exp %in% c("exp13", "exp0")){
    # chinese 
    # no abe is kissing lily 
    # 1  2  3   4       5   
    # 不 张 悦 亲 了 王 平 
    # 1  2  3   4  5 6   7  
    df_Agent = df[(df$location_condition=='Agent' | df$location_condition=='Control') & df$word_num=='2',]
    # df_Agent inheri row hum from df
    
    df_Verb = df[(df$location_condition=='Verb'| df$location_condition=='Control') & df$word_num=='4',]
    
    df_Patient = df[(df$location_condition=='Patient'| df$location_condition=='Control') & df$word_num=='6',]
  } else{
    df_Agent = df[(df$location_condition=='Agent' | df$location_condition=='Control') & df$word_num=='2',]
    # df_Agent inheri row hum from df
    
    df_Verb = df[(df$location_condition=='Verb'| df$location_condition=='Control') & df$word_num=='4',]
    
    df_Patient = df[(df$location_condition=='Patient'| df$location_condition=='Control') & df$word_num=='5',]
    
  }
  
  
  # print(sum(is.na(df_Agent)))
  
  
  print(sum(is.na(df[df$word != 'sp',])))
  # df1[(df1$meanpit == '--undefined--') && (df1$word != 'sp'),]
  # it seems that the only undefined is meanpitch for sp
  
  # print(df_Verb)
  
  df_Verb = normalize_data(df_Verb, bRemove_outliers)
  df_Agent = normalize_data(df_Agent, bRemove_outliers)
  df_Patient = normalize_data(df_Patient, bRemove_outliers)
  # print(sum(is.na(df_Agent)))
  
  
  # return(list(df_Agent_duration, df_Agent_meanIntensity, df_Agent_meanpit, df_Patient_duration, df_Patient_meanIntensity, df_Patient_meanpit,df_Verb_duration, df_Verb_meanIntensity, df_Verb_meanpit))
  return(list(df_Verb, df_Agent, df_Patient))
}

process_data_without_yes = function(df){
  df_Agent = df[ df$location_condition!='Control' & df$word_num=='2',]
  # df_Agent inheri row hum from df
  
  df_Verb = df[ df$location_condition!='Control' & df$word_num=='4',]
  
  
  df_Patient = df[ df$location_condition!='Control' & df$word_num=='5',]
  
  df_Agent$location_condition = mapvalues(df_Agent$location_condition, from=c("Patient", "Verb"), to=c('Control', 'Control'))
  
  df_Verb$location_condition = mapvalues(df_Verb$location_condition, from=c("Agent", "Patient"), to=c('Control', 'Control'))
  
  df_Patient$location_condition = mapvalues(df_Patient$location_condition, from=c("Agent", "Verb"), to=c('Control', 'Control'))
  
  # print(sum(is.na(df_Agent)))
  
  
  print(sum(is.na(df[df$word != 'sp',])))
  
  
  
  df_Verb = normalize_data(df_Verb, bRemove_outliers)
  df_Agent = normalize_data(df_Agent, bRemove_outliers)
  df_Patient = normalize_data(df_Patient, bRemove_outliers)
  # print(sum(is.na(df_Agent)))
  
  
  
  return(list(df_Verb, df_Agent, df_Patient))
}





run_regression = function(location,observation){
  cat("  \n###", observation, "of", location, "  \n")
  r = lmer(get(observation) ~ location_condition + (1 + location_condition|participant) + (1 + location_condition | item_id), data=get(paste0("df_", location)))
  # r = lmer(get(observation) ~ location_condition  + (1 + location_condition | item_id), data=get(paste0("df_", location)))
  print(summary(r))
  summary(r)
  cat("  \n")
}

```



```{r}
# 
# location_condition is an attribute of the trials with levels Agent, patient, verb, and control.
# locaiton is an attribute of the word with levels Agent, patient, verb
# condition is an attribute of the trial with levels contrast and control. 

cur_exp = "exp0"
features = c("duration", "meanIntensity", "meanpit")
# info = c('participant','verb','condition', 'word', 'word_num')
info = c('participant','item_id','location_condition', 'word', 'word_num', 'present_num')
bRemove_outliers = 0
# I have experimented with removing outliers, it doesn't have much effect on duration, some people with extreme pitch or intensity get removed. 

tAll_trials = read.csv(file.path('..', cur_exp, 'tAll_trials.csv'))


# df0 = read.csv(paste0('measure_', cur_exp, '.csv'), header = T)
df0 = read.csv(paste0('measure_', cur_exp, '.csv'))

df0$location_condition = NA
df0$item_id = NA

for (iR in 1:nrow(df0)){
  df0$location_condition[iR] =  as.character(tAll_trials[tAll_trials$trial_id == df0$trialId[iR],'location_condition'])
  df0$item_id[iR] =  as.character(tAll_trials[tAll_trials$trial_id == df0$trialId[iR],'filler_or_item_id'])
  df0$present_num[iR] = as.numeric(rownames(tAll_trials[tAll_trials$trial_id == df0$trialId[iR],]))
}


df1 = df0[startsWith(df0$item_id, "item"),]

# df0 = read.csv("measure_nonrhyming_84total_60No_24Yes_20181210.csv", header  = T)
# df0 = transform(df0,trialId=as.numeric(trialId))
# sort(df0$trialId, decreasing = FALSE)
# colnamesC(df1)

df2 = df1[df1$word != 'sp',] # there can be sp everywhere not just begginning or end
# code for word_num
df2 <- df2 %>% 
  dplyr::group_by(participant, trialId) %>%
  # dplyr::group_by(participant, question, trialId) %>%
  dplyr::mutate(word_num=1:dplyr::n()) %>%
  dplyr::select(c(info, features))

# c(df_Verb, df_Agent, df_Patient) %<-% process_data_with_yes(df2)
c(df_Verb, df_Agent, df_Patient) %<-% process_data_without_yes(df2)
# the agent diff is smaller without yes than yes, maybe because when correcting, agent is stressed even though agent is the the focus

if(cur_exp %in% c("exp4", "exp6", "exp8")){
  df_Agent$condition = mapvalues(df_Agent$location_condition,c('Agent'),c('contrastive no'))
  df_Verb$condition = mapvalues(df_Verb$location_condition,c('Agent'),c('noncontrastive no'))
  df_Patient$condition = mapvalues(df_Patient$location_condition,c('Agent'),c('noncontrastive no'))
} else{
  df_Agent$condition = mapvalues(df_Agent$location_condition,c('Agent'),c('contrast'))
  df_Verb$condition = mapvalues(df_Verb$location_condition,c('Verb'),c('contrast'))
  df_Patient$condition = mapvalues(df_Patient$location_condition,c('Patient'),c('contrast'))  
}


df_Agent$Location = 'Agent'
df_Verb$Location = 'Verb'
df_Patient$Location = "Patient"


combined_dataset = rbind(df_Agent,df_Verb,df_Patient)

# http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/

for (iF in features){
  print(iF)
  
  summarized_dataset = summarySE(combined_dataset,measurevar=iF ,groupvars=c('Location','condition'))
  
  print(
    ggplot(summarized_dataset, aes(x=Location, y=get(iF), fill=condition)) + 
      geom_bar(position=position_dodge(), stat="identity") +
      geom_errorbar(aes(ymin=get(iF)-ci, ymax=get(iF)+ci),
                    width=.2,
                    position=position_dodge(.9))+
      xlab("Location") +
      ylab(paste0("normalized ", iF)) +
      # scale_fill_hue(name="location_condition", 
      #                breaks=c("Control", "contrast"),
      #                labels=c("NonContrastive", "Contrastive")) +
      ggtitle(paste0('Effect of contrast on ', iF ))
  )
}


ggplot(df_Agent, aes(x=present_num, y=duration, color=condition)) +
  geom_point() + geom_smooth(method=lm) + ggtitle("Agent word durations decrease over trials")


ggplot(df_Verb, aes(x=present_num, y=duration, color=condition)) +
  geom_point() + geom_smooth(method=lm) + ggtitle("Verb word durations decrease over trials")

ggplot(df_Patient, aes(x=present_num, y=duration, color=condition)) +
  geom_point() + geom_smooth(method=lm) + ggtitle("Patient word durations decrease over trials")
```


## `r nlevels(df1$participant)` workers and `r nrow(df2)/5` trials are included in this analysis. 

### This the analysis for `r cur_exp`. The parameters of all exps can be seen at https://github.com/Xinzhu-Fang/prosody_study_exp/blob/master/tAll_exps.csv.

### The trial-by-trial design of this exp can be seen at https://github.com/Xinzhu-Fang/prosody_study_exp/blob/master/`r cur_exp`/tAll_trials.csv

### Some code are hidden for the convenience of viewing results. Full code can be found at https://github.com/Xinzhu-Fang/prosody_study_exp/blob/master/analysis/acoustic_analysis.Rmd





<!-- # ```{r, results="asis"} -->
```{r}




# for (iF in features){
#   run_regression("Agent",iF)
#   
#   
#   run_regression("Patient", iF)
#   
#   run_regression("Verb", iF)
#   
#   
#   
# }
# r = lmer(get(observation) ~ condition + (1 | participant) + (1 | verb), data=df)

```

